apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-health-frontend
  namespace: patient-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-health-frontend
  template:
    metadata:
      labels:
        app: patient-health-frontend
    spec:
      imagePullSecrets:
      - name: ibm-cr-secret
      containers:
      - name: frontend
        image: us.icr.io/patient-health-dev/patient-health-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: patient-health-frontend
  namespace: patient-health
spec:
  selector:
    app: patient-health-frontend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: patient-health-frontend
  namespace: patient-health
spec:
  host: patient-health-frontend-patient-health.ibm-openshift-demo-v3-ocp-54fa7508143d3371d96d96009b6a6e9a-0000.us-south.containers.appdomain.cloud
  to:
    kind: Service
    name: patient-health-frontend
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
